[2024-07-05T09:49:21.227+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T09:49:21.246+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T09:48:51.074261+00:00 [queued]>
[2024-07-05T09:49:21.252+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T09:48:51.074261+00:00 [queued]>
[2024-07-05T09:49:21.252+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-05T09:49:21.264+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): run_postgre_docker> on 2024-07-05 09:48:51.074261+00:00
[2024-07-05T09:49:21.268+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T09:49:21.269+0000] {standard_task_runner.py:63} INFO - Started process 199 to run task
[2024-07-05T09:49:21.269+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'prod_dag', 'run_postgre_docker', 'manual__2024-07-05T09:48:51.074261+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/DAG_prod.py', '--cfg-path', '/tmp/tmp2qs5w1mp']
[2024-07-05T09:49:21.270+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask run_postgre_docker
[2024-07-05T09:49:21.305+0000] {task_command.py:426} INFO - Running <TaskInstance: prod_dag.run_postgre_docker manual__2024-07-05T09:48:51.074261+00:00 [running]> on host d1b8fc7d37d2
[2024-07-05T09:49:21.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prod_dag' AIRFLOW_CTX_TASK_ID='run_postgre_docker' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T09:48:51.074261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T09:48:51.074261+00:00'
[2024-07-05T09:49:21.369+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T09:49:21.391+0000] {docker.py:366} INFO - Starting docker container from image bost67dst/postgre_loading
[2024-07-05T10:11:01.823+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-05T10:11:01.824+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-05T10:11:01.825+0000] {process_utils.py:132} INFO - Sending 15 to group 199. PIDs of all processes in the group: [199]
[2024-07-05T10:11:01.825+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 199
[2024-07-05T10:11:01.825+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-05T10:11:01.825+0000] {docker.py:528} INFO - Stopping docker container
[2024-07-05T10:11:12.036+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T10:11:12.088+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=199, status='terminated', exitcode=0, started='09:49:20') (199) terminated with exit code 0
